"""
Plan Entitlements.
"""

PLAN_ENTITLEMENTS = {
    "BRONZE": {
        "included": [
            "General Balance (Till yesterday end in PDF format)",
            "Track",
            "Commercial Checking/Savings Account/Foreign account Statements",
            "Customer Insight Statements",
            "All Notification (Billable and Non-billable)",
        ],
        "optional": [
            "Reject Payments and modify Notices",
            "Deposit correction",
            "Account Balance (with Direct API integration)",
        ],
    },
    "SILVER": {
        "included": [
            "General Balance (Till yesterday end in PDF format)",
            "Previous Day combined (balance and detail)",
            "Track",
            "Image (view and print images for checks and deposits)",
            "Commercial Checking/Savings Account/Foreign account Statements",
            "Customer Insight Statements",
            "All Notification (Billable and Non-billable)",
        ],
        "optional": [
            "DDA Account periodic statement (Format other than PDF)",
            "Monthly Progress Balance",
            "Reject Payments and modify Notices",
            "Deposit correction",
            "Account Balance (with Direct API integration)",
            "Account Balance (with customer portal)",
            "Payment Detail (with Direct API integration)",
            "Payment Detail (with Portal connect)",
            "Image",
            "Yesterday",
            "Transmitted EBS",
            "Direct BAI Standard",
        ],
    },
    "GOLD": {
        "included": [
            "General Balance (Till yesterday end in PDF format)",
            "Previous Day combined (balance and detail)",
            "Instant combined (balance and detail)",
            "Wire tracking detail",
            "ACH Inbound detail",
            "Internet Banking",
            "Track",
            "Image (view and print images for checks and deposits)",
            "Expanded transaction Detail",
            "Commercial Checking/Savings Account/Foreign account Statements",
            "Customer Insight Statements",
            "All Notification (Billable and Non-billable)",
        ],
        "optional": [
            "DDA Account periodic statement (Format other than PDF)",
            "Monthly Progress Balance",
            "Deposit Review report",
            "Present Position",
            "Reject Payments and modify Notices",
            "Deposit correction",
            "Account Balance (with Direct API integration)",
            "Account Balance (with customer portal)",
            "Payment Detail (with Direct API integration)",
            "Payment Detail (with Portal connect)",
            "Image",
            "Payment expanded detail",
            "Yesterday",
            "Transmitted EBS",
            "Direct BAI Standard",
            "Intraday and expanded detail",
            "Direct BAI Premium",
            "Deposit detail",
            "Present Day",
            "History with expanded details",
            "Payments gbf",
        ],
    },
    # Reports/services not included in any data plan; available only as paid add-ons.
    "PAID": {
        "reports": [
            "ACH Customer Activity",
            "ACH Subscription",
            "ACH Exception Status",
            "ACH Outbound",
            "ACH Return/Change",
            "PRA Data Query",
            "PRA Statement and Optional Report Subscription",
            "PRA Statements & Reports (CSV/Excel)",
            "PRA Statements & Reports (PDF)",
            "PRA File Posting Confirmation (PDF)",
            "Organized flow Subscription",
            "Organized flow Detail",
            "Organized flow Summary",
            "Electronic collection bag",
            "QAZ Subscription",
            "QAZ Payment Detail (CCD+/CTX)",
            "LENDING Manager Subscription",
            "Collectioning Detail",
            "Collectioning Subscription",
            "Collectioning Availability",
            "Returned Item subscription",
            "Today Return Item Detail",
            "Yesterday Return Item Detail",
            "Sweep Subscription",
            "Sweep Account Position",
        ]
    },
}
